name: Tests

on:
  workflow_run:
    workflows: ["Push Workflow"]
    types:
      - completed

jobs:
  test_job:
    runs-on: ubuntu-latest
    - name: Run Tests
      run: bash tests/example_test.sh 
