# Use $ to signify pointers
# folder_name: $filename

# model, dataset, and experiment are "import" keys
model: $UNet
dataset: CSE275_HW0
experiment: standard_experiment

# Train, Test
mode: train
val: 0.2

seed: 0
epochs: 1
batch_size: 64
num_workers: 4
learning_rate: 0.0001
weight_decay: 0.0001

torchinfo: True

# !! IMPORTANT INNATE VARIABLES
# config.enable_output = whether or not outputs are enabled. This should usually be True.
# config.path.data = dataset location
# config.path.output = output location for this experiment 
# config.path.weights = weights location for this experiment

# !! These also exist, but you don't really need them
# config.id.name = experiment name
# config.id.workdir = working directory this was called from
# config.config_path = path to the saved config
