# Use $ to signify pointers
# folder_name: $filename

# model, dataset, and experiment are "import" keys
model: $UNet
dataset: CSE275_HW0
experiment: standard_experiment

# Train, Test
mode: train
val: 0.2

seed: 0
epochs: 1
batch_size: 64
num_workers: 4
learning_rate: 0.0001
weight_decay: 0.0001

torchinfo: True
