name: push

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      TEMP_REPO_TAG: mlplatform-image-base
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker Encryption
        run: |
          sudo apt-get update
          sudo apt-get install -y pass
          curl -fsSL https://github.com/docker/docker-credential-helpers/releases/download/v0.8.0/docker-credential-pass-v0.8.0.linux-amd64 -o docker-credential-pass
          chmod +x docker-credential-pass
          mv docker-credential-pass /usr/local/bin/
      - name: Initialize Pass
        run: |
          echo "%echo Generating a basic OpenPGP key
          Key-Type: default
          Subkey-Type: default
          Name-Real: CI
          Name-Comment: Temporary Key for CI
          Name-Email: ci@localhost
          Expire-Date: 0
          %no-protection
          %commit
          %echo done" | gpg2 --batch --pinentry-mode loopback --gen-key
          pass init "ci@localhost"
          echo '{"credHelpers": {"ghcr.io": "pass"}}' > ~/.docker/config.json
      - name: Docker Login
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin
      - name: Build
        run: bash docker/base/build.sh ${TEMP_REPO_TAG}
      - name: Push
        run: |
          LOWERCASE_IMAGE_REPO=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          docker tag ${TEMP_REPO_TAG} ghcr.io/${LOWERCASE_IMAGE_REPO}-image-base:latest
          docker push ghcr.io/${LOWERCASE_IMAGE_REPO}-image-base:latest

  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Tests
        run: bash tests/example_test.sh 
