name: push
on: [push]
env:
  BUILD_BASE: true
  IMAGE_REPO_TAG_BASE: image-base:latest
  DOCKER_DIR_BASE: docker/base
  IMAGE_REPO_TAG: image:latest
  DOCKER_DIR: docker/dev

jobs:
  GHCR:
    runs-on: ubuntu-latest
    outputs:
      GHCR_IMAGE_REPO_TAG_BASE: ${{ steps.variables.outputs.GHCR_IMAGE_REPO_TAG_BASE }}
      GHCR_IMAGE_REPO_TAG: ${{ steps.variables.outputs.GHCR_IMAGE_REPO_TAG }}
      PROJECT_NAME: ${{ steps.variables.outputs.PROJECT_NAME }}
    steps:
      - name: GHCR Formatting
        id: variables
        run: |
          LOWERCASE_GITHUB_REPO=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          GHCR_IMAGE_REPO_TAG_BASE=${LOWERCASE_GITHUB_REPO}/${{ env.IMAGE_REPO_TAG_BASE }}
          GHCR_IMAGE_REPO_TAG=${LOWERCASE_GITHUB_REPO}/${{ env.IMAGE_REPO_TAG }}
          echo "GHCR_IMAGE_REPO_TAG_BASE=${GHCR_IMAGE_REPO_TAG_BASE}" >> "$GITHUB_OUTPUT"
          echo "GHCR_IMAGE_REPO_TAG=${GHCR_IMAGE_REPO_TAG}" >> "$GITHUB_OUTPUT"
          echo "PROJECT_NAME=${GITHUB_REPOSITORY##*/}" >> "$GITHUB_OUTPUT"
  build_base:
    needs: GHCR
    if: github.environment.env.BUILD_BASE == 'true'
    runs-on: ubuntu-latest
    env:
      GHCR_IMAGE_REPO_TAG_BASE: ${{ needs.GHCR.outputs.GHCR_IMAGE_REPO_TAG_BASE }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Encryption
        run: chmod +x ./.github/encryption/install.sh && ./.github/encryption/install.sh
      - name: Generate Encryption
        run: chmod +x ./.github/encryption/generate.sh && ./.github/encryption/generate.sh
      - name: Docker Login
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: GHCR Pull
        run: docker pull ghcr.io/${GHCR_IMAGE_REPO_TAG_BASE} || true
      - name: Docker Build
        run: bash ${{ env.DOCKER_DIR_BASE }}/build.sh ghcr.io/${GHCR_IMAGE_REPO_TAG_BASE}
      - name: GHCR Push
        run: |
          docker push ghcr.io/${GHCR_IMAGE_REPO_TAG_BASE}
  build:
    needs: build_base
    runs-on: ubuntu-latest
    env:
      GHCR_IMAGE_REPO_TAG_BASE: ${{ needs.GHCR.outputs.GHCR_IMAGE_REPO_TAG_BASE }}
      GHCR_IMAGE_REPO_TAG: ${{ needs.GHCR.outputs.GHCR_IMAGE_REPO_TAG }}
      PROJECT_NAME: ${{ needs.GHCR.outputs.PROJECT_NAME }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Encryption
        run: chmod +x ./.github/encryption/install.sh && ./.github/encryption/install.sh
      - name: Generate Encryption
        run: chmod +x ./.github/encryption/generate.sh && ./.github/encryption/generate.sh
      - name: Docker Login
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: GHCR Pull
        run: docker pull ghcr.io/${GHCR_IMAGE_REPO_TAG} || true
      - name: Docker Build
        run: bash ${{ env.DOCKER_DIR }}/build.sh ghcr.io/${GHCR_IMAGE_REPO_TAG_BASE} ghcr.io/${GHCR_IMAGE_REPO_TAG} ${PROJECT_NAME}
      - name: GHCR Push
        run: |
          docker push ghcr.io/${GHCR_IMAGE_REPO_TAG}
  tests:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ needs.GHCR.outputs.GHCR_IMAGE_REPO_TAG }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Tests
        run: bash tests/example_test.sh 
