name: push

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      TEMP_REPO_TAG: mlplatform-image-base
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker Login
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin
      - name: Build
        run: bash docker/base/build.sh ${TEMP_REPO_TAG}
      - name: Push
        run: |
          LOWERCASE_IMAGE_REPO=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          docker tag ${TEMP_REPO_TAG} ghcr.io/${LOWERCASE_IMAGE_REPO}-image-base:latest
          docker push ghcr.io/${LOWERCASE_IMAGE_REPO}-image-base:latest

  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Tests
        run: bash tests/example_test.sh 
