name: push
on: [push]
env:
  BUILD_BASE: false
  IMAGE_REPO_TAG_BASE: image-base:latest
  DOCKER_DIR_BASE: docker/base
  IMAGE_REPO_TAG: image:latest
  DOCKER_DIR: docker/dev

jobs:
  global:
    runs-on: ubuntu-latest
    outputs:
      BUILD_BASE: ${{ steps.variables.outputs.BUILD_BASE }}
      GHCR_IMAGE_REPO_TAG_BASE: ${{ steps.variables.outputs.GHCR_IMAGE_REPO_TAG_BASE }}
      GHCR_IMAGE_REPO_TAG: ${{ steps.variables.outputs.GHCR_IMAGE_REPO_TAG }}
      PROJECT_NAME: ${{ steps.variables.outputs.PROJECT_NAME }}
    steps:
      - name: Set Global Variables
        id: variables
        run: |
          LOWERCASE_GITHUB_REPO=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          GHCR_IMAGE_REPO_TAG_BASE=${LOWERCASE_GITHUB_REPO}/${{ env.IMAGE_REPO_TAG_BASE }}
          GHCR_IMAGE_REPO_TAG=${LOWERCASE_GITHUB_REPO}/${{ env.IMAGE_REPO_TAG }}
          echo "GHCR_IMAGE_REPO_TAG_BASE=${GHCR_IMAGE_REPO_TAG_BASE}" >> "$GITHUB_OUTPUT"
          echo "GHCR_IMAGE_REPO_TAG=${GHCR_IMAGE_REPO_TAG}" >> "$GITHUB_OUTPUT"
          echo "PROJECT_NAME=${GITHUB_REPOSITORY##*/}" >> "$GITHUB_OUTPUT"
          echo "BUILD_BASE=${{ env.BUILD_BASE }}" >> "$GITHUB_OUTPUT"
  build_base:
    needs: 
      - global
    runs-on: ubuntu-latest
    env:
      BUILD_BASE: ${{ needs.global.outputs.BUILD_BASE }}
      GHCR_IMAGE_REPO_TAG_BASE: ${{ needs.global.outputs.GHCR_IMAGE_REPO_TAG_BASE }}
    steps:
      - name: Check Build Base Skip Condition
        run: echo "BUILD_BASE == ${{ env.BUILD_BASE }}"
      - name: Checkout
        if: env.BUILD_BASE == 'true'
        uses: actions/checkout@v4
      # - name: Install Encryption
      #   if: env.BUILD_BASE == 'true'
      #   run: chmod +x ./.github/encryption/install.sh && ./.github/encryption/install.sh
      # - name: Generate Encryption
      #   if: env.BUILD_BASE == 'true'
      #   run: chmod +x ./.github/encryption/generate.sh && ./.github/encryption/generate.sh
      - name: Docker Login
        if: env.BUILD_BASE == 'true'
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: GHCR Pull
        if: env.BUILD_BASE == 'true'
        run: docker pull ghcr.io/${GHCR_IMAGE_REPO_TAG_BASE} || true
      - name: Docker Build
        if: env.BUILD_BASE == 'true'
        run: bash ${{ env.DOCKER_DIR_BASE }}/build.sh ghcr.io/${GHCR_IMAGE_REPO_TAG_BASE}
      - name: GHCR Push
        if: env.BUILD_BASE == 'true'
        run: docker push ghcr.io/${GHCR_IMAGE_REPO_TAG_BASE}
  # build:
  #   needs: 
  #     - global
  #     - build_base
  #   runs-on: ubuntu-latest
  #   env:
  #     GHCR_IMAGE_REPO_TAG_BASE: ${{ needs.global.outputs.GHCR_IMAGE_REPO_TAG_BASE }}
  #     GHCR_IMAGE_REPO_TAG: ${{ needs.global.outputs.GHCR_IMAGE_REPO_TAG }}
  #     PROJECT_NAME: ${{ needs.global.outputs.PROJECT_NAME }}
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #     # - name: Install Encryption
  #     #   run: chmod +x ./.github/encryption/install.sh && ./.github/encryption/install.sh
  #     # - name: Generate Encryption
  #     #   run: chmod +x ./.github/encryption/generate.sh && ./.github/encryption/generate.sh
  #     - name: Docker Login
  #       run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
  #     - name: GHCR Pull
  #       run: docker pull ghcr.io/${GHCR_IMAGE_REPO_TAG} || true
  #     - name: Docker Build
  #       run: bash ${{ env.DOCKER_DIR }}/build.sh ghcr.io/${GHCR_IMAGE_REPO_TAG_BASE} ghcr.io/${GHCR_IMAGE_REPO_TAG} ${PROJECT_NAME}
  #     - name: GHCR Push
  #       run: docker push ghcr.io/${GHCR_IMAGE_REPO_TAG}
  tests:
    needs:
      - global
    runs-on: ubuntu-latest
    env:
      WORKDIR: /app/${{ needs.global.outputs.PROJECT_NAME }}
    container:
      image: ghcr.io/${{ needs.global.outputs.GHCR_IMAGE_REPO_TAG }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}
    defaults:
      run:
        working-directory: ${WORKDIR}
    steps: # No checkout, only use whats in docker
      - name: Verify Container
        run: whoami
      - name: Run Tests
        run: bash tests/example_test.sh 
